# Generated by Django 3.2.3 on 2021-05-31 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CRUDOperations',
            new_name='CRUDOperation',
        ),
    ]
