# Generated by Django 3.2.3 on 2021-05-31 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_crudoperations_crudoperation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CRUDOperation',
            new_name='Post',
        ),
    ]
